version: '3.1'

services:
  springboot:
    image: docker13143/spring-boot-mongo:VERSION
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=Rocky
    - MONGO_DB_PASSWORD=Bhai
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork  
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=Rocky
    - MONGO_INITDB_ROOT_PASSWORD=Bhai
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    
networks:
  springappnetwork:
